<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>Assets\app_icon.ico</ApplicationIcon>
    <Authors>Tyrlov R.V</Authors>
    <Copyright>Copyright © 2026 Тырлов Ростислав Викторович. Все права защищены.</Copyright>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Assets\app_icon.ico" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Views\" />
    <Folder Include="Properties\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ClosedXML" Version="0.105.1" />
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    <PackageReference Include="LiveChartsCore.SkiaSharpView.WPF" Version="2.0.5" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.0.12" />
    <PackageReference Include="QuestPDF" Version="2026.9.0" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Assets\app_icon.ico" />
  </ItemGroup>

</Project>
